baseURL: https://jesus-tuesta.netlify.app/
languageCode: en-us
title: Portfolio website for Jesus Tuesta
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Curious analyst and looking to create impact in the financial world with quantitative tools
    title: Jesus Tuesta
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 1 North Bank, Flat 33, Regent Court
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: anderson.tuestas@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44) 7376 467899
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School - Data Science in R
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.london.edu/
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/andergod
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jesus-tuesta/
  image: ''
  name: Your name
  navigation:
    links:
      - name: Home
        url: /
      - name: About Myself
        url: blogs/biography
      - name: Projects
        url: blogs/risk_return
      - name: Resume
        url: blogs/risk_return
    menu: Menu
    subtitle:
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: Jesus-MachuPichu.jpg
        subtitle: Myself and my history
        title: About Myself
        url: blogs/biography
      - image: Data-analysis.jpg
        subtitle: Practical showcase of my experience
        title: Projects
        url: post/2023-06-26-index-for-projects
      - image: Jesus-UP.png
        subtitle: Follow my journey so far
        title: Resume
        url: blogs/risk_return
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hi, my name is Jesus Tuesta. I am ambitious economist looking to understand more about the financial
    world using quantitative tools to explore it. I finished  my Master in Financial
    Analysis (MFA2023) at London Business School. I also have a Bachelor in Economics from the Universidad del 
    Pacífico (UP) in Peru and Bsc. in Economics & Finance at University from The University of London with First Class 
    Honours. I am proficient in SQL, R, Python, Microsoft Excel (VBA) and Bloomberg."
    title: Short Bio
    url: /
